name: RPM Build

env:
  version: ${{github.ref_name}}
  release: 1
  draft: true

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build RPM package
      id: buildrpm7
      uses: carlospeon/buildrpm@centos7
      with:
        spec: contrib/collectd.spec
        version: ${{ env.version }}
        release: ${{ env.release }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el7-rpms.zip \
          ${{ steps.buildrpm7.outputs.rpms_path }}/x86_64/*.el7.x86_64.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el7-rpms-debuginfo.zip \
          ${{ steps.buildrpm7.outputs.rpms_path }}/x86_64/*-debuginfo-*.el7.x86_64.rpm

    - name: build RPM package
      id: buildrpm8
      uses: carlospeon/buildrpm@rocky8
      with:
        spec: contrib/collectd.spec
        version: ${{ env.version }}
        release: ${{ env.release }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el8-rpms.zip \
          ${{ steps.buildrpm8.outputs.rpms_path }}/x86_64/*.el8.x86_64.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el8-rpms-debuginfo.zip \
          ${{ steps.buildrpm8.outputs.rpms_path }}/x86_64/*-debuginfo-*.el8.x86_64.rpm

    - name: build RPM package
      id: buildrpm9
      uses: carlospeon/buildrpm@rocky9
      with:
        spec: contrib/collectd.spec
        version: ${{ env.version }}
        release: ${{ env.release }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el9-rpms.zip \
          ${{ steps.buildrpm9.outputs.rpms_path }}/x86_64/*.el9.x86_64.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el9-rpms-debuginfo.zip \
          ${{ steps.buildrpm9.outputs.rpms_path }}/x86_64/*-debuginfo-*.el9.x86_64.rpm

    - uses: ncipollo/release-action@v1
      with:
        name: collectd-${{ env.version }}
        artifacts: "collectd-${{ env.version }}-${{ env.release }}-*-rpms*.zip"
        artifactContentType: application/zip
        replacesArtifacts: true
        allowUpdates: true
        draft: ${{ env.draft }}
