name: RPM Build

env:
  tag: ${{ github.ref_name }}
  draft: true

on: 
  push:
    tags:
    - 'collectd-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get version
      id: version
      run: |
        version=$(echo ${{ env.tag }} | cut -d - -f 2)
        echo "version=${version}" >> $GITHUB_OUTPUT

    - name: checkout
      uses: actions/checkout@v3

    - name: build RPM package
      id: buildrpm7
      uses: carlospeon/buildrpm@centos7
      with:
        spec: contrib/redhat/collectd.spec
        version: ${{ steps.version.outputs.version }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ steps.version.outputs.version }}-el7-x86_64-rpms.zip \
          ${{ steps.buildrpm7.outputs.rpms_path }}/x86_64/*.el7.x86_64.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ steps.version.outputs.version }}-el7-x86_64-rpms-debuginfo.zip \
          ${{ steps.buildrpm7.outputs.rpms_path }}/x86_64/*-debuginfo-*.el7.x86_64.rpm

    - name: build RPM package
      id: buildrpm8
      uses: carlospeon/buildrpm@rocky8
      with:
        spec: contrib/redhat/collectd.spec
        version: ${{ steps.version.outputs.version }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ steps.version.outputs.version }}-el8-x86_64-rpms.zip \
          ${{ steps.buildrpm8.outputs.rpms_path }}/x86_64/*.el8.x86_64.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ steps.version.outputs.version }}-el8-x86_64-rpms-debuginfo.zip \
          ${{ steps.buildrpm8.outputs.rpms_path }}/x86_64/*-debuginfo-*.el8.x86_64.rpm

    - name: build RPM package
      id: buildrpm9
      uses: carlospeon/buildrpm@rocky9
      with:
        spec: contrib/redhat/collectd.spec
        version: ${{ steps.version.outputs.version }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ steps.version.outputs.version }}-el9-x86_64-rpms.zip \
          ${{ steps.buildrpm9.outputs.rpms_path }}/x86_64/*.el9.x86_64.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ steps.version.outputs.version }}-el9-x86_64-rpms-debuginfo.zip \
          ${{ steps.buildrpm9.outputs.rpms_path }}/x86_64/*-debuginfo-*.el9.x86_64.rpm

    - uses: ncipollo/release-action@v1
      with:
        name: collectd-${{ steps.version.outputs.version }}
        artifacts: "collectd-${{ steps.version.outputs.version }}-*-x86_64-rpms*.zip"
        artifactContentType: application/zip
        replacesArtifacts: true
        allowUpdates: true
        draft: ${{ env.draft }}

