name: RPM Build

env:
  version: ${{github.ref_name}}
  release: 1
  draft: true

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build RPM package
      id: buildrpm
      uses: carlospeon/buildrpm@rocky9
      with:
        spec: contrib/collectd.spec
        version: ${{ env.version }}
        release: ${{ env.release }}

    - name: zip rpms
      run: |
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el9-rpms.zip \
          ${{ steps.buildrpm.outputs.rpms_path }}/x86_64/*.rpm \
          -x "*-debuginfo-*"
        zip --junk-paths \
          collectd-${{ env.version }}-${{ env.release }}-el9-rpms-debuginfo.zip \
          ${{ steps.buildrpm.outputs.rpms_path }}/x86_64/*-debuginfo-*.rpm \

    - uses: ncipollo/release-action@v1
      with:
        name: collectd-${{ env.version }}
        tag: ${{ env.version }}
        artifacts: "collectd-${{ env.version }}-${{ env.release }}-*-rpms*.zip"
        artifactContentType: application/zip
        replacesArtifacts: true
        allowUpdates: true
        draft: ${{ env.draft }}
